spring:
  datasource:
    username: root
    password: r12201517@R
    url: jdbc:mysql://localhost:3306/movies
    driver-class-name: com.mysql.cj.jdbc.Driver  # Ensure the driver is specified
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
server:
    port: 8081
project:
  poster: C:/Users/Rohit Ranjan/Desktop/SpringBoot/movieApi/movieApi/poster/

